name: GitHub Stats Card

on:
  schedule:
    # Roda a cada 8 horas
    - cron: '0 */8 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update README with stats
        uses: anuraghazra/github-readme-stats@master
        with:
          # O token do GitHub é necessário para acessar a API
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Opções para o cartão de estatísticas
          SHOW_ICONS: true
          THEME: radical
          INCLUDE_ALL_COMMITS: true
          COUNT_PRIVATE: true
