# Nome do Workflow
name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
      
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - uses: Platane/snk@v3
        with:
          github_user_name: arthurtschinkel25
          
          outputs: output/snake.svg
        
      - name: Commit and Push snake.svg
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add output/snake.svg
          # Verifica se há mudanças antes de tentar fazer o commit
          if git diff --staged --quiet; then
            echo "Nenhuma mudança na animação, commit não é necessário."
          else
            git commit -m "feat: update snake contribution grid"
            git push
          fi
